---
- name: Deploy Dockerized application
  hosts: app_server
  become: yes

  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Log in to Docker Hub
      ansible.builtin.command:
        cmd: docker login -u {{ docker_user }} -p {{ docker_pass }}
      no_log: true

    - name: Pull the latest Docker image
      ansible.builtin.command:
        cmd: docker pull {{ docker_image }}

    - name: Stop and remove existing container (if any)
      ansible.builtin.command:
        cmd: docker rm -f petstore || true

    - name: Run the Docker container
      ansible.builtin.command:
        cmd: docker run -d --name petstore -p 8080:8080 {{ docker_image }}

    - name: Log out from Docker Hub
      ansible.builtin.command:
        cmd: docker logout
