all:
  hosts:
    app_server:
      ansible_host: "{{ target_server_ip }}"  # variable would be passed through jenkins
      ansible_user: ubuntu               
      ansible_ssh_private_key_file: "{{ ssh_key }}" # variable would be passed through jenkins
        
